using Content.Shared._Starlight.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class ClearLagWindow : DefaultWindow
{
    /// <summary>Raised when the player clicks "Clear" for a category.</summary>
    public event Action<ClearLagCategory>? OnClear;

    /// <summary>Raised when the player clicks "Refresh Counts".</summary>
    public event Action? OnRefresh;

    public ClearLagWindow()
    {
        RobustXamlLoader.Load(this);

        ClearTrashButton.OnPressed        += _ => OnClear?.Invoke(ClearLagCategory.Trash);
        ClearSpentCasingsButton.OnPressed += _ => OnClear?.Invoke(ClearLagCategory.SpentCasings);
        ClearSovietCratesButton.OnPressed += _ => OnClear?.Invoke(ClearLagCategory.SovietArmsCrates);
        RefreshButton.OnPressed           += _ => OnRefresh?.Invoke();
    }

    /// <summary>Updates the displayed counts for each category.</summary>
    public void UpdateCounts(int trash, int spentCasings, int sovietCrates)
    {
        TrashCount.Text        = trash.ToString();
        SpentCasingsCount.Text = spentCasings.ToString();
        SovietCratesCount.Text = sovietCrates.ToString();
    }
}
