using System.Numerics;
using Content.Shared._Starlight.Canvas;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;

namespace Content.Client._Starlight.Canvas;

[GenerateTypedNameReferences]
public sealed partial class SpriteCanvasWindow : DefaultWindow
{
    // ── Events ─────────────────────────────────────────────────────────────────
    public event Action<List<CanvasStroke>>? OnSaveRequested;
    public event Action?                     OnClearRequested;
    public event Action?                     OnSignRequested;

    // ── Constants ──────────────────────────────────────────────────────────────
    private const int SwatchSize = 22;
    private const int SwatchPad  = 3;

    // ── Internal state ─────────────────────────────────────────────────────────
    private int         _maxStrokes;
    private CanvasSize? _currentCanvasSize;
    private bool        _isSigned;

    private readonly List<PanelContainer> _swatchPanels = new();
    private int _activeSwatchIndex = 1; // default = black

    public SpriteCanvasWindow()
    {
        Title = Loc.GetString("sprite-canvas-title");
        RobustXamlLoader.Load(this);

        // Build colour palette
        BuildPalette();

        // Brush-size buttons
        BrushSmall.OnPressed  += _ => SelectBrush(0);
        BrushMedium.OnPressed += _ => SelectBrush(1);
        BrushLarge.OnPressed  += _ => SelectBrush(2);

        EraserButton.OnPressed += _ =>
        {
            DrawingCanvas.SetEraser(true);
            EraserButton.Disabled = true;
        };

        // Default: medium brush, black colour
        DrawingCanvas.SetBrushSize(SpriteCanvasControl.BrushSizes[1]);
        DrawingCanvas.SetColor(SpriteCanvasControl.Palette[1]);
        BrushSizeInput.Text = SpriteCanvasControl.BrushSizes[1].ToString("0.#");

        // Hex colour input — update preview as the user types, apply on Enter
        HexInput.OnTextChanged += _ => OnHexTextChanged();
        HexInput.OnTextEntered += _ => ApplyHexColor();

        // Custom brush size input — apply on Enter
        BrushSizeInput.OnTextEntered += _ => ApplyCustomBrushSize();

        // Save / Clear
        SaveButton.OnPressed += _ =>
        {
            if (!DrawingCanvas.HasPendingStrokes) return;
            var strokes = DrawingCanvas.TakeAndClearPending();
            OnSaveRequested?.Invoke(strokes);
        };

        ClearButton.OnPressed += _ => OnClearRequested?.Invoke();

        // Sign button
        SignButton.OnPressed += _ => OnSignRequested?.Invoke();

        // Update stroke counter whenever a stroke finishes
        DrawingCanvas.OnStrokeCompleted += _ => UpdateStrokeCount();
    }

    // ── Public API ─────────────────────────────────────────────────────────────
    public void Populate(SpriteCanvasBuiState state, bool canEdit)
    {
        _maxStrokes = 512;

        // Resize canvas control when size category changes
        if (_currentCanvasSize != (CanvasSize)(int)state.CanvasSize)
        {
            _currentCanvasSize = (CanvasSize)(int)state.CanvasSize;
            var px = CanvasSizePx(state.CanvasSize);
            DrawingCanvas.SetWidth  = px;
            DrawingCanvas.SetHeight = px;
        }

        DrawingCanvas.SetStrokes(state.Strokes);
        UpdateStrokeCount(state.Strokes.Count);
        UpdateSignedState(state.IsSigned, state.SignedBy, canEdit);
    }

    // ── Private helpers ────────────────────────────────────────────────────────
    private static int CanvasSizePx(CanvasSizeType type) => type switch
    {
        CanvasSizeType.Small  => 500,
        CanvasSizeType.Medium => 1000,
        CanvasSizeType.Large  => 1500,
        _                     => 500,
    };

    private void BuildPalette()
    {
        for (var i = 0; i < SpriteCanvasControl.Palette.Length; i++)
        {
            var idx   = i;
            var color = SpriteCanvasControl.Palette[i];

            // Single panel: color fill + selection border on the same control.
            // MouseFilter.Stop ensures this panel — not some invisible parent — gets hit-tested.
            var swatch = new PanelContainer
            {
                MinSize = new Vector2(SwatchSize + SwatchPad * 2, SwatchSize + SwatchPad * 2),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor  = color,
                    BorderColor      = Color.Transparent,
                    BorderThickness  = new Thickness(2),
                },
                MouseFilter = MouseFilterMode.Stop,
                ToolTip     = color.ToHex(),
            };

            swatch.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick) return;
                SelectSwatch(idx);
                args.Handle();
            };

            _swatchPanels.Add(swatch);
            PaletteRow.AddChild(swatch);
        }

        SelectSwatch(_activeSwatchIndex);
    }

    private void SelectSwatch(int index)
    {
        if (_activeSwatchIndex >= 0 && _activeSwatchIndex < _swatchPanels.Count)
            if (_swatchPanels[_activeSwatchIndex].PanelOverride is StyleBoxFlat prev)
                prev.BorderColor = Color.Transparent;

        _activeSwatchIndex = index;
        if (_swatchPanels[index].PanelOverride is StyleBoxFlat flat)
            flat.BorderColor = Color.White;

        var color = SpriteCanvasControl.Palette[index];
        DrawingCanvas.SetColor(color);
        DrawingCanvas.SetEraser(false);
        EraserButton.Disabled = false;

        // Mirror into the hex input
        HexInput.Text = color.ToHex().TrimStart('#');
        UpdateHexPreview(color);
    }

    private void SelectBrush(int sizeIndex)
    {
        DrawingCanvas.SetBrushSize(SpriteCanvasControl.BrushSizes[sizeIndex]);
        BrushSizeInput.Text = SpriteCanvasControl.BrushSizes[sizeIndex].ToString("0.#");
        DrawingCanvas.SetEraser(false);
        EraserButton.Disabled = false;
    }

    // ── Hex colour input ───────────────────────────────────────────────────────
    private void OnHexTextChanged()
    {
        if (TryParseHex(HexInput.Text, out var color))
            UpdateHexPreview(color);
    }

    private void ApplyHexColor()
    {
        if (!TryParseHex(HexInput.Text, out var color)) return;

        // Deselect any swatch (border stays; we don't pick a swatch index)
        if (_activeSwatchIndex >= 0 && _activeSwatchIndex < _swatchPanels.Count)
            if (_swatchPanels[_activeSwatchIndex].PanelOverride is StyleBoxFlat prev)
                prev.BorderColor = Color.Transparent;
        _activeSwatchIndex = -1;

        DrawingCanvas.SetColor(color);
        DrawingCanvas.SetEraser(false);
        EraserButton.Disabled = false;
        UpdateHexPreview(color);
    }

    private void UpdateHexPreview(Color color)
    {
        if (HexPreview.PanelOverride is StyleBoxFlat flat)
            flat.BackgroundColor = color;
        else
            HexPreview.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
    }

    private static bool TryParseHex(string input, out Color color)
    {
        color = Color.Black;
        var s = input.Trim().TrimStart('#');
        if (s.Length is not (6 or 8)) return false;
        try { color = Color.FromHex("#" + s); return true; }
        catch { return false; }
    }

    // ── Custom brush size input ────────────────────────────────────────────────
    private void ApplyCustomBrushSize()
    {
        if (!float.TryParse(BrushSizeInput.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var size))
            return;
        size = Math.Clamp(size, 1f, 50f);
        DrawingCanvas.SetBrushSize(size);
        BrushSizeInput.Text = size.ToString("0.#");
    }

    // ── Signed state ───────────────────────────────────────────────────────────
    private void UpdateSignedState(bool isSigned, string? signedBy, bool canEdit)
    {
        _isSigned = isSigned;

        if (isSigned)
        {
            // Show locked banner
            LockedBanner.Visible = true;
            LockedLabel.Text     = Loc.GetString("sprite-canvas-locked", ("name", signedBy ?? "?"));

            // Show signed-by in bottom bar
            SignedByLabel.Text   = Loc.GetString("sprite-canvas-signed-by", ("name", signedBy ?? "?"));
            SignButton.Visible   = false;

            // Lock or unlock drawing based on whether this player has override access
            DrawingCanvas.SetLocked(!canEdit);
            SaveButton.Disabled  = !canEdit;
            ClearButton.Disabled = !canEdit;
        }
        else
        {
            LockedBanner.Visible = false;
            SignedByLabel.Text   = string.Empty;
            SignButton.Visible   = true;
            DrawingCanvas.SetLocked(false);
            SaveButton.Disabled  = false;
            ClearButton.Disabled = false;
        }
    }

    private void UpdateStrokeCount(int committed = 0)
    {
        var pending = DrawingCanvas.HasPendingStrokes ? 1 : 0; // approximate
        StrokeCountLabel.Text = Loc.GetString("sprite-canvas-stroke-count",
            ("count", committed + pending),
            ("max",   _maxStrokes));
    }

    // Private enum to track resize state without re-evaluating every frame
    private enum CanvasSize { Small, Medium, Large }
}
