using Content.Shared._Starlight.AmmoAutoloader;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.AmmoAutoloader.UI;

[GenerateTypedNameReferences]
public sealed partial class AmmoAutoloaderWindow : DefaultWindow
{
    private readonly IEntityManager _entMan;

    public event Action? ToggleSide1;
    public event Action? ToggleSide2;
    public event Action? EjectMag1;
    public event Action? EjectMag2;
    public event Action? EjectAmmo1;
    public event Action? EjectAmmo2;

    public AmmoAutoloaderWindow()
    {
        RobustXamlLoader.Load(this);

        _entMan = IoCManager.Resolve<IEntityManager>();

        Side1ToggleButton.OnPressed += _ => ToggleSide1?.Invoke();
        Side2ToggleButton.OnPressed += _ => ToggleSide2?.Invoke();
        Side1EjectMagButton.OnPressed  += _ => EjectMag1?.Invoke();
        Side2EjectMagButton.OnPressed  += _ => EjectMag2?.Invoke();
        Side1EjectAmmoButton.OnPressed += _ => EjectAmmo1?.Invoke();
        Side2EjectAmmoButton.OnPressed += _ => EjectAmmo2?.Invoke();
    }

    public void UpdateState(AmmoAutoloaderBuiState state)
    {
        // ── Jam banner ────────────────────────────────────────────────────────────
        JamBanner.Visible = state.IsJammed;

        // ── Side 1 ────────────────────────────────────────────────────────────────
        Side1MagName.Text  = state.Side1MagName  ?? Loc.GetString("ammo-autoloader-empty");
        Side1AmmoName.Text = state.Side1AmmoName ?? Loc.GetString("ammo-autoloader-empty");

        SetCompatLabel(Side1CompatLabel, state.Side1HasMag && state.Side1HasAmmo, state.Side1Compatible);
        SetStatusLabel(Side1StatusLabel, state.Side1AutoLoad, state.IsJammed, state.JammedSide == 1);
        SetToggleButton(Side1ToggleButton, state.Side1AutoLoad, state.IsJammed || !state.Side1HasMag || !state.Side1HasAmmo);

        if (state.Side1MagEntity != null)
            Side1MagSprite.SetEntity(_entMan.GetEntity(state.Side1MagEntity.Value));
        else
            Side1MagSprite.SetEntity(null);

        // ── Side 2 ────────────────────────────────────────────────────────────────
        Side2MagName.Text  = state.Side2MagName  ?? Loc.GetString("ammo-autoloader-empty");
        Side2AmmoName.Text = state.Side2AmmoName ?? Loc.GetString("ammo-autoloader-empty");

        SetCompatLabel(Side2CompatLabel, state.Side2HasMag && state.Side2HasAmmo, state.Side2Compatible);
        SetStatusLabel(Side2StatusLabel, state.Side2AutoLoad, state.IsJammed, state.JammedSide == 2);
        SetToggleButton(Side2ToggleButton, state.Side2AutoLoad, state.IsJammed || !state.Side2HasMag || !state.Side2HasAmmo);

        if (state.Side2MagEntity != null)
            Side2MagSprite.SetEntity(_entMan.GetEntity(state.Side2MagEntity.Value));
        else
            Side2MagSprite.SetEntity(null);
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────────

    private static void SetCompatLabel(Label label, bool hasBoth, bool compatible)
    {
        if (!hasBoth)
        {
            label.Text       = Loc.GetString("ammo-autoloader-compat-unknown");
            label.FontColorOverride = null;
            return;
        }

        if (compatible)
        {
            label.Text              = Loc.GetString("ammo-autoloader-compat-yes");
            label.FontColorOverride = Color.FromHex("#44cc44");
        }
        else
        {
            label.Text              = Loc.GetString("ammo-autoloader-compat-no");
            label.FontColorOverride = Color.FromHex("#cc4444");
        }
    }

    private static void SetStatusLabel(Label label, bool autoLoad, bool jammed, bool thisSideJammed)
    {
        if (thisSideJammed)
        {
            label.Text              = Loc.GetString("ammo-autoloader-status-jammed");
            label.FontColorOverride = Color.FromHex("#cc4444");
        }
        else if (jammed)
        {
            label.Text              = Loc.GetString("ammo-autoloader-status-idle");
            label.FontColorOverride = null;
        }
        else if (autoLoad)
        {
            label.Text              = Loc.GetString("ammo-autoloader-status-loading");
            label.FontColorOverride = Color.FromHex("#44cc44");
        }
        else
        {
            label.Text              = Loc.GetString("ammo-autoloader-status-idle");
            label.FontColorOverride = null;
        }
    }

    private static void SetToggleButton(Button button, bool autoLoad, bool disabled)
    {
        button.Disabled = disabled;
        button.Pressed  = autoLoad;
        button.Text     = autoLoad
            ? Loc.GetString("ammo-autoloader-autoload-on")
            : Loc.GetString("ammo-autoloader-autoload-off");
    }
}
