- type: antag
  id: WesternDragon
  name: ghost-role-information-western-dragon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-western-dragon-objective
  playTimeTracker: AntagWesternDragon
