using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Message;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.ArmsVendor.UI;

[GenerateTypedNameReferences]
public sealed partial class ArmsVendorMenu : DefaultWindow
{
    /// <summary>
    /// Hardcoded ammo type display for known weapon entities.
    /// </summary>
    private static readonly Dictionary<string, string> AmmoTypes = new()
    {
        { "WeaponSubMachineGunWt550",       ".35 Auto"      },
        { "WeaponSubMachineGunC20r",        ".35 Auto"      },
        { "WeaponSubMachineGunDrozd",       ".35 Auto"      },
        { "WeaponSubMachineGunBriefcase",   ".35 Auto"      },
        { "Stunbaton",                       "N/A"   },
        { "WeaponDisablerSMG",               "N/A"  },
        { "EnergySword",                     "N/A"   },
        { "EnergySwordDouble",               "N/A"   },
        { "GrenadeFlashBang",                "None"         },
    };

    public event Action<ListingDataWithCostModifiers>? OnBuyPressed;

    private readonly IPrototypeManager _protoManager;
    private ListingDataWithCostModifiers? _selectedListing;

    public ArmsVendorMenu()
    {
        RobustXamlLoader.Load(this);

        _protoManager = IoCManager.Resolve<IPrototypeManager>();

        BuyButton.OnPressed += _ =>
        {
            if (_selectedListing != null)
                OnBuyPressed?.Invoke(_selectedListing);
        };
    }

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        if (balance.TryGetValue("ArmsTicket", out var amount))
            BalanceLabel.Text = $"Balance: {(int)amount} arms tickets";
        else
            BalanceLabel.Text = "Balance: 0 arms tickets";
    }

    public event Action<ProtoId<StoreCategoryPrototype>>? OnCategorySelected;

    public void PopulateCategories(IEnumerable<ProtoId<StoreCategoryPrototype>> categoryIds)
    {
        CategoryContainer.DisposeAllChildren();

        foreach (var categoryId in categoryIds)
        {
            if (!_protoManager.TryIndex(categoryId, out var catProto))
                continue;

            var button = new Button
            {
                Text = Loc.GetString(catProto.Name),
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };
            var capturedId = categoryId;
            button.OnPressed += _ =>
            {
                _selectedListing = null;
                ClearDetailPanel();
                OnCategorySelected?.Invoke(capturedId);
            };
            CategoryContainer.AddChild(button);
        }
    }

    public void PopulateItems(IEnumerable<ListingDataWithCostModifiers> listings)
    {
        ItemListContainer.DisposeAllChildren();

        foreach (var listing in listings)
        {
            var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(listing, _protoManager);
            var cost = GetArmsCost(listing);

            var button = new Button
            {
                Text = $"{name}  —  {cost} tickets",
                HorizontalExpand = true,
                Margin = new Thickness(2, 1),
            };
            var capturedListing = listing;
            button.OnPressed += _ =>
            {
                _selectedListing = capturedListing;
                ShowDetailPanel(capturedListing);
            };
            ItemListContainer.AddChild(button);
        }
    }

    private void ShowDetailPanel(ListingDataWithCostModifiers listing)
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(listing, _protoManager);
        ItemNameLabel.Text = name;

        var cost = GetArmsCost(listing);
        ItemCostLabel.Text = $"Cost: {cost}";
        ItemCostSuffix.Text = " arms tickets";

        // Sprite
        if (listing.ProductEntity != null)
            ItemSpriteView.SetPrototype(listing.ProductEntity);

        // Description — split off ammo type if description contains newline
        var rawDesc = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(listing, _protoManager);

        string ammoText = string.Empty;
        string descText = rawDesc;

        // Check hardcoded ammo dict first
        if (listing.ProductEntity != null && AmmoTypes.TryGetValue(listing.ProductEntity, out var knownAmmo))
        {
            ammoText = knownAmmo;
        }
        else if (rawDesc.Contains('\n'))
        {
            // Description was formatted with ammo type on first line
            var idx = rawDesc.IndexOf('\n');
            ammoText = rawDesc[..idx].Trim();
            descText = rawDesc[(idx + 1)..].Trim();
        }

        if (!string.IsNullOrWhiteSpace(ammoText))
        {
            AmmoContainer.Visible = true;
            ItemAmmoLabel.Text = ammoText;
        }
        else
        {
            AmmoContainer.Visible = false;
            ItemAmmoLabel.Text = string.Empty;
        }

        ItemDescriptionLabel.SetMarkup(descText);
        BuyButton.Disabled = false;
    }

    private void ClearDetailPanel()
    {
        ItemNameLabel.Text = "Select an item";
        ItemCostLabel.Text = string.Empty;
        ItemCostSuffix.Text = string.Empty;
        ItemSpriteView.SetPrototype((EntProtoId?) null);
        AmmoContainer.Visible = false;
        ItemAmmoLabel.Text = string.Empty;
        ItemDescriptionLabel.SetMarkup(string.Empty);
        BuyButton.Disabled = true;
    }

    private static int GetArmsCost(ListingDataWithCostModifiers listing)
    {
        return listing.Cost.TryGetValue("ArmsTicket", out var c) ? (int)c : 0;
    }
}
