using Content.Client.Medical.Cryogenics;
using Content.Shared._Starlight.AlloySmeltery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.AlloySmeltery.UI;

[GenerateTypedNameReferences]
public sealed partial class AlloySmelteryWindow : DefaultWindow
{
    public AlloySmelteryWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AlloySmelteryBuiState state)
    {
        MaterialList.RemoveAllChildren();

        if (state.Materials.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("alloy-smeltery-ui-empty");
            return;
        }

        var capacity = Math.Max(state.DisplayCapacity, 1);

        foreach (var entry in state.Materials)
        {
            var chart = new BeakerBarChart
            {
                Capacity = capacity,
                HorizontalExpand = true,
                MinHeight = 24,
                MaxHeight = 24,
            };

            chart.Clear();
            chart.SetEntry(
                entry.MaterialId,
                Loc.GetString("alloy-smeltery-ui-material-entry",
                    ("material", entry.LocalizedName),
                    ("amount", entry.Amount)),
                entry.Amount,
                entry.Color,
                tooltip: $"{entry.LocalizedName}: {entry.Amount} / {capacity}");

            MaterialList.AddChild(chart);
        }

        StatusLabel.Text = Loc.GetString("alloy-smeltery-ui-total",
            ("count", state.Materials.Count));
    }
}
